const livros = [
  {titulo: "Dom Quixote", preco: 35.99},
  {titulo: "Orgulho ePrecoceito", preco: 24.50},
  {titulo: "Cem Anos de Solidão", preco: 28.75},
  {titulo: "1984", preco: 20.00},
  {titulo: "O Senhor dos Anéis", preco: 40.25},
  {titulo: "Harry Potter e a Pedra Filosofal", preco: 22.99},
  {titulo: "A Menina que Roubava Livros", preco: 18.75},
  {titulo: "O Hobbit", preco: 30.50},
  {titulo: "A Revolução dos Bichos", preco: 15.99},
  {titulo: "O Pequeno Príncipe", preco: 19.25},
  {titulo: "Crime e Castigo", preco: 27.00},
  {titulo: "Memórias Póstumas de Brás Cubas", preco: 21.50},
  {titulo: "Moby Dick", preco: 32.75},
  {titulo: "O Morro dos Ventos Uivantes", preco: 26.99},
  {titulo: "O Conde de Monte Cristo", preco: 36.50},
  {titulo: "A Metamorfose", preco: 17.75},
  {titulo: "Anna Karenina", preco: 29.00},
  {titulo: "A Insustentável Leveza do Ser", preco: 23.25},
  {titulo: "As Crônicas de Nárnia", preco: 38.99},
  {titulo: "O Retrato de Dorian Gray", preco: 25.75},
  {titulo: "O Nome do Vento", preco: 31.00},
  {titulo: "O Apanhador no Campo de Centeio", preco: 20.25},
  {titulo: "A Culpa é das Estrelas", preco: 16.50},
  {titulo: "O Labirinto dos Espíritos", preco: 34.75},
  {titulo: "A Sombra do Vento", preco: 27.99},
  {titulo: "A Revolta de Atlas", preco: 42.50},
  {titulo: "A Cabana", preco: 19.75},
  {titulo: "As Vinhas da Ira", preco: 23.00},
  {titulo: "O Sol é para Todos", preco: 28.25},
  {titulo: "O Iluminado", preco: 36.99},
  {titulo: "O Silmarillion", preco: 31.25},
  {titulo: "O Código Da Vinci", preco: 25.50},
  {titulo: "A Bússola de Ouro", preco: 22.75},
  {titulo: "A Hospedeira", preco: 18.00},
  {titulo: "As Aventuras de Huckleberry Finn", preco: 29.25},
  {titulo: "O Jogo do Anjo", preco: 33.50},
  {titulo: "O Poder do Hábito", preco: 17.75},
  {titulo: "O Diário de Anne Frank", preco: 21.00},
  {titulo: "A Hora da Estrela", preco: 24.25},
  {titulo: "A Estrada", preco: 30.99},
  {titulo: "O Primo Basílio", preco: 35.25},
  {titulo: "O Mundo de Sofia", preco: 26.50},
  {titulo: "O Alquimista", preco: 20.75},
  {titulo: "Cemitério Maldito", preco: 16.00},
  {titulo: "A Menina Submersa: Memórias", preco: 19.25},
  {titulo: "A Garota no Trem", preco: 25.50},
  {titulo: "A Hora da Verdade", preco: 31.75},
  {titulo: "O Sol Também é uma Estrela", preco: 28.99},
  {titulo: "O Orfanato da Srta. Peregrine Para Crianças Peculiares", preco: 34.25},
  {titulo: "O Mágico de Oz", preco: 22.50},
  {titulo: "A Redoma de Vidro", preco: 18.75},
  {titulo: "O Ilustre Senhor Ripley", preco: 23.00},
  {titulo: "As Aventuras de Sherlock Holmes", preco: 29.25},
  {titulo: "O Conto da Aia", preco: 35.50},
  {titulo: "A Escolha de Sofia", preco: 20.75},
  {titulo: "A Livraria 24 Horas do Mr. Penumbra", preco: 17.00},
  {titulo: "A Cor Púrpura", preco: 21.25},
  {titulo: "O Vento nos Salgueiros", preco: 27.99},
  {titulo: "A Lua de Joana", preco: 34.25},
  {titulo: "O Tempo e o Vento", preco: 22.50},
  {titulo: "As Vantagens de Ser Invisível", preco: 18.75},
  {titulo: "O Símbolo Perdido", preco: 23.00},
  {titulo: "A Cidade do Sol", preco: 29.25},
  {titulo: "O Diabo Veste Prada", preco: 35.50},
  {titulo: "O Fim da Eternidade", preco: 20.75},
  {titulo: "O Cão dos Baskervilles", preco: 17.00},
  {titulo: "O Festim dos Corvos", preco: 21.25},
  {titulo: "O Lobo da Estepe", preco: 27.99},
  {titulo: "A Marca de uma Lágrima", preco: 34.25},
  {titulo: "A Arte da Guerra", preco: 22.50},
  {titulo: "O Apanhador de Sonhos", preco: 18.75},
  {titulo: "O Médico e o Monstro", preco: 23.00},
  {titulo: "A Cidade do Fogo Celestial", preco: 29.25},
  {titulo: "O Demonologista", preco: 35.50},
  {titulo: "A Longa Viagem a um Pequeno Planeta Hostil", preco: 20.75},
  {titulo: "O Lado Bom da Vida", preco: 17.00},
  {titulo: "O Velho e o Mar", preco: 21.25},
  {titulo: "A Estrada da Noite", preco: 27.99},
  {titulo: "O Médico", preco: 34.25},
  {titulo: "A Montanha Mágica", preco: 22.50},
  {titulo: "O Menino do Pijama Listrado", preco: 18.75},
  {titulo: "O Reverso da Medalha", preco: 23.00},
  {titulo: "A Vida Invisível de Eurídice Gusmão", preco: 29.25},
  {titulo: "O Projeto Rosie", preco: 35.50},
  {titulo: "A Viagem do Elefante", preco: 20.75},
  {titulo: "O Poderoso Chefão", preco: 17.00},
  {titulo: "O Guardião de Memórias", preco: 21.25},
  {titulo: "A Princesa Prometida", preco: 27.99},
  {titulo: "O Velho que Lia Romances de Amor", preco: 34.25},
  {titulo: "A Dança da Morte", preco: 22.50},
  {titulo: "O Símbolo Perdido", preco: 18.75},
  {titulo: "O Herói Discreto", preco: 23.00},
  {titulo: "A Trégua", preco: 29.25},
  {titulo: "O Labirinto de Osiris", preco: 35.50},
  {titulo: "A História de Edgar Sawtelle", preco: 20.75},
  {titulo: "O Conde de Abranhos", preco: 17.00},
  {titulo: "O Leitor", preco: 21.25},
  {titulo: "A Cúpula", preco: 27.99},
  {titulo: "O Oceano no Fim do Caminho", preco: 34.25},
  {titulo: "A Menina que Roubava Livros", preco: 22.50},
  {titulo: "O Pequeno Príncipe", preco: 18.75},
  {titulo: "A Queda de Gondolin", preco: 23.00},
  {titulo: "O Guia do Mochileiro das Galáxias", preco: 29.25},
  {titulo: "A Arte de Fazer Acontecer", preco: 35.50},
  {titulo: "O Prisioneiro do Céu", preco: 20.75},
  {titulo: "A Noite das Bruxas", preco: 17.00},
  {titulo: "O Sol nasce Sempre", preco: 21.25},
  {titulo: "A Árvore da Mente", preco: 27.99},
  {titulo: "O Diário de um Mago", preco: 34.25},
  {titulo: "A Arte da Sabedoria", preco: 22.50},
  {titulo: "O Lado Escuro da Lua", preco: 18.75},
  {titulo: "A Vida e Morte de Charlie St. Cloud", preco: 23.00},
  {titulo: "O Anjo da Morte", preco: 29.25},
  {titulo: "A Garota na Teia de Aranha", preco: 35.50},
  {titulo: "O Sol é Para Todos", preco: 20.75},
  {titulo: "A Hora da Estrela", preco: 17.00},
  {titulo: "O Príncipe da Névoa", preco: 21.25},
  {titulo: "A Caçada", preco: 27.99},
  {titulo: "O Alquimista", preco: 34.25},
  {titulo: "A Peste", preco: 22.50},
  {titulo: "O Apanhador de Sonhos", preco: 18.75},
  {titulo: "A Conspiração", preco: 23.00},
  {titulo: "O Sussurro", preco: 29.25},
  {titulo: "A Roda do Tempo", preco: 35.50},
  {titulo: "O Grande Gatsby", preco: 20.75},
  {titulo: "A Menina que Brincava com Fogo", preco: 17.00},
  {titulo: "O Vento nos Salgueiros", preco: 21.25},
  {titulo: "A Lua de Joana", preco: 27.99},
  {titulo: "O Tempo e o Vento", preco: 34.25},
  {titulo: "A Revolução dos Bichos", preco: 22.50},
  {titulo: "A Casa das Sete Torres", preco: 18.75},
  {titulo: "O Senhor das Moscas", preco: 23.00},
  {titulo: "A Trilogia de Nova York", preco: 29.25},
  {titulo: "O Pequeno Lorde", preco: 35.50},
  {titulo: "A Arma Escarlate", preco: 20.75},
  {titulo: "A Desumanização", preco: 17.00},
  {titulo: "O Cemitério", preco: 21.25},
  {titulo: "A Fúria dos Reis", preco: 27.99},
  {titulo: "O Enigma do Oito", preco: 34.25},
  {titulo: "A Praia", preco: 22.50},
  {titulo: "O Dragão de Gelo", preco: 18.75},
  {titulo: "A Cidade do Sol", preco: 23.00},
  {titulo: "A Longa Viagem a um Pequeno Planeta Hostil", preco: 29.25},
  {titulo: "O Amor nos Tempos do Cólera", preco: 35.50},
  {titulo: "A Lista de Schindler", preco: 20.75},
  {titulo: "A Última Música", preco: 17.00},
  {titulo: "O Velho que Lia Romances de Amor", preco: 21.25},
  {titulo: "A Dança da Morte", preco: 27.99},
  {titulo: "O Livro dos Baltimore", preco: 34.25},
  {titulo: "A Vida Invisível de Eurídice Gusmão", preco: 22.50},
  {titulo: "O Vampiro Lestat", preco: 18.75},
  {titulo: "A Descoberta das Bruxas", preco: 23.00},
  {titulo: "O Rouxinol", preco: 29.25},
  {titulo: "A Estrada da Noite", preco: 35.50},
  {titulo: "O Segredo do Meu Marido", preco: 20.75},
  {titulo: "A Vida que Ninguém Vê", preco: 17.00},
  {titulo: "O Guia do Mochileiro das Galáxias", preco: 21.25},
  {titulo: "A Arte de Correr na Chuva", preco: 27.99},
  {titulo: "O Poder da Esperança", preco: 34.25},
  {titulo: "A Cabana", preco: 22.50},
  {titulo: "O Lobo da Estepe", preco: 18.75},
  {titulo: "A Janela de Overton", preco: 23.00},
  {titulo: "O Conto da Aia", preco: 29.25},
  {titulo: "O Papai é Pop", preco: 35.50},
  {titulo: "A Hospedeira", preco: 20.75},
  {titulo: "O Sol Também é uma Estrela", preco: 17.00},
  {titulo: "O Mundo de Sofia", preco: 21.25},
  {titulo: "A Sombra do Vento", preco: 27.99},
  {titulo: "O Retrato de Dorian Gray", preco: 34.25},
  {titulo: "A Morte do Demônio", preco: 22.50},
  {titulo: "O Chamado do Cuco", preco: 18.75},
  {titulo: "A Arte da Guerra", preco: 23.00},
  {titulo: "O Cão dos Baskervilles", preco: 29.25},
  {titulo: "O Silmarillion", preco: 35.50},
  {titulo: "A Menina Submersa: Memórias", preco: 20.75},
  {titulo: "O Pássaro", preco: 17.00},
  {titulo: "A Garota no Trem", preco: 21.25},
  {titulo: "O Orfanato da Srta. Peregrine Para Crianças Peculiares", preco: 27.99},
  {titulo: "O Casamento", preco: 34.25},
  {titulo: "A Maldição do Tigre", preco: 22.50},
  {titulo: "O Rouxinol", preco: 18.75},
  {titulo: "A Tormenta de Espadas", preco: 23.00},
  {titulo: "O Mundo de Gelo e Fogo", preco: 29.25},
  {titulo: "O Circo da Noite", preco: 35.50},
  {titulo: "A Pirâmide Vermelha", preco: 20.75},
  {titulo: "O Garoto do Cachecol Vermelho", preco: 17.00},
  {titulo: "A Maldição do Titã", preco: 21.25},
  {titulo: "O Hobbit", preco: 27.99},
  {titulo: "O Nome do Vento", preco: 34.25},
  {titulo: "A Queda dos Reinos", preco: 22.50},
  {titulo: "O Apanhador no Campo de Centeio", preco: 18.75},
  {titulo: "A Cidade do Fogo Celestial", preco: 23.00},
  {titulo: "O Mar de Monstros", preco: 29.25},
  {titulo: "A Maldição do Vencedor", preco: 35.50},
  {titulo: "O Sol é para Todos", preco: 20.75},
  {titulo: "A Culpa é das Estrelas", preco: 17.00},
  {titulo: "O Labirinto dos Espíritos", preco: 21.25},
  {titulo: "O Silmarillion", preco: 27.99},
  {titulo: "A Escolha dos Três", preco: 34.25},
  {titulo: "O Código Da Vinci", preco: 22.50},
  {titulo: "A Revolução dos Bichos", preco: 18.75},
  {titulo: "O Chamado do Cuco", preco: 23.00},
  {titulo: "O Senhor dos Anéis", preco: 29.25},
  {titulo: "A Garota que Você Deixou para Trás", preco: 35.50},
  {titulo: "O Livro do Amanhã", preco: 20.75},
  {titulo: "A Livraria 24 Horas do Mr. Penumbra", preco: 17.00},
  {titulo: "O Castelo de Vidro", preco: 21.25},
  {titulo: "O Oceano no Fim do Caminho", preco: 27.99},
]

module.exports = livros
